// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using hometask5.Models;

#nullable disable

namespace hometask5.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("hometask5.Models.Analysis", b =>
                {
                    b.Property<int>("AnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("an_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnId"));

                    b.Property<decimal>("AnCost")
                        .HasColumnType("money")
                        .HasColumnName("an_cost");

                    b.Property<int>("AnGroup")
                        .HasColumnType("int")
                        .HasColumnName("an_group");

                    b.Property<string>("AnName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("an_name");

                    b.Property<decimal>("AnPrice")
                        .HasColumnType("money")
                        .HasColumnName("an_price");

                    b.HasKey("AnId")
                        .HasName("PK__Analysis__831DABF3C016F1F2");

                    b.HasIndex("AnGroup");

                    b.HasIndex(new[] { "AnName" }, "UQ__Analysis__251E3FCD0619E067")
                        .IsUnique();

                    b.ToTable("Analysis", (string)null);
                });

            modelBuilder.Entity("hometask5.Models.Group", b =>
                {
                    b.Property<int>("GrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("gr_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrId"));

                    b.Property<string>("GrName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("gr_name");

                    b.Property<double>("GrTemp")
                        .HasColumnType("float")
                        .HasColumnName("gr_temp");

                    b.HasKey("GrId")
                        .HasName("PK__Groups__2BC0F88EBD58F738");

                    b.HasIndex(new[] { "GrName" }, "UQ__Groups__2291CF8D1E34F79C")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("hometask5.Models.Order", b =>
                {
                    b.Property<int>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ord_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdId"));

                    b.Property<int>("OrdAn")
                        .HasColumnType("int")
                        .HasColumnName("ord_an");

                    b.Property<DateTime>("OrdDatetime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ord_datetime");

                    b.HasKey("OrdId")
                        .HasName("PK__Orders__DC39D7DFF1FDB40D");

                    b.HasIndex("OrdAn");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("hometask5.Models.Analysis", b =>
                {
                    b.HasOne("hometask5.Models.Group", "AnGroupNavigation")
                        .WithMany("Analyses")
                        .HasForeignKey("AnGroup")
                        .IsRequired()
                        .HasConstraintName("FK__Analysis__an_gro__3B75D760");

                    b.Navigation("AnGroupNavigation");
                });

            modelBuilder.Entity("hometask5.Models.Order", b =>
                {
                    b.HasOne("hometask5.Models.Analysis", "OrdAnNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("OrdAn")
                        .IsRequired()
                        .HasConstraintName("FK__Orders__ord_an__3E52440B");

                    b.Navigation("OrdAnNavigation");
                });

            modelBuilder.Entity("hometask5.Models.Analysis", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("hometask5.Models.Group", b =>
                {
                    b.Navigation("Analyses");
                });
#pragma warning restore 612, 618
        }
    }
}
